### ISSUE TITLE
sail-to-lean: project milestones

### ISSUE THREAD

**Issue by tobiasgrosser** [rems-project/sail#837]
- [x] support the sail prelude
- [x] https://alasdair.github.io/manual.html#_a_tutorial_risc_v_style_example
- [x] https://github.com/rems-project/sail-tiny-arm

**Comment by jprider63** [comment]
@javra is planning to go through these early models and start creating issues that breaks down which AST elements need to be implemented. If you start working on one of these, assign the issue to yourself so that multiple people don't work on the same one.

**Comment by javra** [comment]
`examples/riscv-dupod.sail` actually doesn't compile right now, for some reason it complains about a "Redundant wildcard clause"

**Comment by bacam** [comment]
That should just be a warning.

**Comment by tobiasgrosser** [comment]
This has all been addressed.
